version: '3.4'

services:
  app_produto:
   image: produto/web
   container_name: Cadastro_Produto
   expose:
   - "8080"
   ports: 
   - "8080:80"
   depends_on:
     - db
  db:
    image: mysql
    container_name: db_dados
    environment:
     -MYSQL_USER: root
     -MYSQL_ROOT_PASSWORD: dell9888
     -MYSQL_DATABASE: Dados_Produto
    volumes:
     - ./docker/mysql_volume:/var/lib/mysql
   